import React from 'react';
import { useNavigate } from 'react-router-dom';

export default function TermsPage() {
  const navigate = useNavigate();

  return (
    <div style={{ background: '#020617', minHeight: '100vh', color: '#f8fafc', fontFamily: 'DM Sans, sans-serif' }}>
      <nav style={{ padding: '0 5vw', height: 72, display: 'flex', alignItems: 'center', borderBottom: '1px solid #1e293b', background: '#020617' }}>
        <button onClick={() => navigate('/')} style={{ background: 'transparent', border: 'none', color: '#94a3b8', cursor: 'pointer', fontSize: 14, fontWeight: 700, display: 'flex', alignItems: 'center', gap: 8 }}>
          ← Back to Home
        </button>
      </nav>

      <div style={{ maxWidth: 800, margin: '0 auto', padding: '60px 5vw 120px' }}>
        <h1 style={{ fontSize: 40, fontWeight: 800, marginBottom: 16, letterSpacing: '-0.02em', color: '#f8fafc' }}>Terms of Service</h1>
        <p style={{ color: '#94a3b8', fontSize: 16, marginBottom: 40 }}>Last Updated: May 31, 2026</p>

        <section style={{ marginBottom: 40, color: '#cbd5e1', lineHeight: 1.8 }}>
          <h2 style={{ fontSize: 24, fontWeight: 700, color: '#f8fafc', marginBottom: 16 }}>1. Acceptance of Terms</h2>
          <p style={{ marginBottom: 16 }}>
            By accessing or using GitGrade ("the Service"), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you do not have permission to access the Service.
          </p>
        </section>

        <section style={{ marginBottom: 40, color: '#cbd5e1', lineHeight: 1.8 }}>
          <h2 style={{ fontSize: 24, fontWeight: 700, color: '#f8fafc', marginBottom: 16 }}>2. Description of Service</h2>
          <p style={{ marginBottom: 16 }}>
            GitGrade provides AI-powered developer tooling designed to analyze, grade, and generate documentation for public GitHub repositories. The Service relies on external APIs (such as the GitHub REST API and Google Gemini AI) whose availability and performance we do not control.
          </p>
        </section>

        <section style={{ marginBottom: 40, color: '#cbd5e1', lineHeight: 1.8 }}>
          <h2 style={{ fontSize: 24, fontWeight: 700, color: '#f8fafc', marginBottom: 16 }}>3. AI-Generated Content Disclaimer</h2>
          <p style={{ marginBottom: 16 }}>
            The content, code, and documentation generated by GitGrade are produced by Artificial Intelligence. While we strive for accuracy, AI can produce incorrect, misleading, or outdated information ("hallucinations"). <strong>You are solely responsible for reviewing, verifying, and testing any generated code or documentation before using it in a production environment.</strong>
          </p>
        </section>

        <section style={{ marginBottom: 40, color: '#cbd5e1', lineHeight: 1.8 }}>
          <h2 style={{ fontSize: 24, fontWeight: 700, color: '#f8fafc', marginBottom: 16 }}>4. Fair Use and Abuse</h2>
          <p style={{ marginBottom: 16 }}>
            You agree not to misuse the Service or help anyone else do so. For example, you must not:
          </p>
          <ul style={{ paddingLeft: 24, marginBottom: 16 }}>
            <li style={{ marginBottom: 8 }}>Attempt to reverse engineer the Service or bypass our generation limits.</li>
            <li style={{ marginBottom: 8 }}>Use the Service to generate malicious code, spam, or abusive content.</li>
            <li style={{ marginBottom: 8 }}>Submit excessively large repositories aimed at causing Denial of Service.</li>
          </ul>
        </section>

        <section style={{ marginBottom: 40, color: '#cbd5e1', lineHeight: 1.8 }}>
          <h2 style={{ fontSize: 24, fontWeight: 700, color: '#f8fafc', marginBottom: 16 }}>5. Limitation of Liability</h2>
          <p style={{ marginBottom: 16 }}>
            In no event shall GitGrade, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
          </p>
        </section>

        <section style={{ color: '#cbd5e1', lineHeight: 1.8 }}>
          <h2 style={{ fontSize: 24, fontWeight: 700, color: '#f8fafc', marginBottom: 16 }}>6. Changes to Terms</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any significant changes.
          </p>
        </section>
      </div>
    </div>
  );
}
