import { useState } from "react";

const GH = "https://api.github.com";
const RAW = "https://raw.githubusercontent.com";

function parseUrl(url) {
  const m = url.match(/github\.com\/([^/]+)\/([^/\s?#]+)/);
  return m ? { owner: m[1], repo: m[2].replace(/\.git$/, "") } : null;
}
async function ghFetch(path) {
  const r = await fetch(`${GH}${path}`);
  if (!r.ok) return null;
  return r.json();
}
async function tryRaw(owner, repo, file, branch) {
  for (const b of [branch, "main", "master"]) {
    try { const r = await fetch(`${RAW}/${owner}/${repo}/${b}/${file}`); if (r.ok) return r.text(); } catch {}
  }
  return null;
}

// ─── Repo scanner ─────────────────────────────────────────────────────────────
async function scanRepo(owner, repo) {
  const [meta, tree, langs] = await Promise.all([
    ghFetch(`/repos/${owner}/${repo}`),
    ghFetch(`/repos/${owner}/${repo}/git/trees/HEAD?recursive=1`),
    ghFetch(`/repos/${owner}/${repo}/languages`),
  ]);
  if (!meta) throw new Error("Repo not found or is private.");
  const branch = meta.default_branch || "main";
  const files = (tree?.tree || []).filter(f => f.type === "blob");

  // Large files (>500KB by size estimate from GitHub)
  const largeFiles = files
    .filter(f => f.size && f.size > 500000)
    .sort((a, b) => b.size - a.size)
    .slice(0, 20)
    .map(f => ({ path: f.path, size: f.size }));

  // Suspicious / junk patterns
  const junkPatterns = [
    { pattern: /node_modules\//i, label: "node_modules committed", severity: "critical", fix: "Add node_modules/ to .gitignore and remove with git rm -r --cached node_modules" },
    { pattern: /\.DS_Store/i, label: ".DS_Store files", severity: "high", fix: "Add .DS_Store to .gitignore and run: git rm -r --cached **/.DS_Store" },
    { pattern: /Thumbs\.db/i, label: "Thumbs.db files", severity: "medium", fix: "Add Thumbs.db to .gitignore" },
    { pattern: /\.env$/, label: ".env file committed", severity: "critical", fix: "SECURITY RISK: Remove immediately. Use .env.example instead. Rotate any exposed secrets." },
    { pattern: /\.log$/, label: "Log files committed", severity: "high", fix: "Add *.log to .gitignore" },
    { pattern: /dist\/|build\//i, label: "Build artifacts committed", severity: "high", fix: "Add dist/ and build/ to .gitignore unless this is a published package" },
    { pattern: /\.zip$|\.tar\.gz$|\.rar$/i, label: "Archive files", severity: "medium", fix: "Remove archive files — use releases or external storage instead" },
    { pattern: /\.psd$|\.ai$|\.sketch$/i, label: "Design source files", severity: "low", fix: "Consider using Git LFS for large design files or storing externally" },
    { pattern: /coverage\//i, label: "Test coverage reports", severity: "medium", fix: "Add coverage/ to .gitignore — generate locally or in CI" },
    { pattern: /\.pyc$|__pycache__/i, label: "Python cache files", severity: "high", fix: "Add __pycache__/ and *.pyc to .gitignore" },
    { pattern: /\.class$/i, label: "Java .class files", severity: "high", fix: "Add *.class to .gitignore" },
    { pattern: /\.o$|\.a$|\.so$/i, label: "Compiled binary objects", severity: "medium", fix: "Add *.o *.a *.so to .gitignore" },
    { pattern: /secret|password|credential|api.?key/i, label: "Possible secret/credential file", severity: "critical", fix: "Review carefully — never commit secrets. Use environment variables." },
    { pattern: /\.min\.js$/, label: "Minified JS committed", severity: "low", fix: "Minified files should be generated by build process, not committed" },
    { pattern: /vendor\//i, label: "Vendor directory committed", severity: "medium", fix: "Consider using a package manager and .gitignore for vendor/" },
  ];

  const findings = junkPatterns.map(({ pattern, label, severity, fix }) => {
    const matches = files.filter(f => pattern.test(f.path)).map(f => f.path).slice(0, 6);
    return matches.length > 0 ? { label, severity, fix, count: matches.length, examples: matches } : null;
  }).filter(Boolean);

  // Missing important files
  const allPaths = files.map(f => f.path.toLowerCase());
  const missing = [];
  if (!allPaths.some(p => p === ".gitignore")) missing.push({ file: ".gitignore", severity: "critical", fix: "Create a .gitignore file — use gitignore.io to generate one for your stack" });
  if (!allPaths.some(p => p.match(/^readme/i))) missing.push({ file: "README.md", severity: "critical", fix: "Add a README.md — essential for any repo" });
  if (!allPaths.some(p => p.match(/^license/i))) missing.push({ file: "LICENSE", severity: "high", fix: "Add a license file — without one, your code is legally all rights reserved" });
  if (!allPaths.some(p => p.match(/^\.env\.example|env\.example/))) missing.push({ file: ".env.example", severity: "medium", fix: "Add .env.example so collaborators know what environment variables are needed" });
  if (!allPaths.some(p => p.match(/contributing/i))) missing.push({ file: "CONTRIBUTING.md", severity: "low", fix: "Add CONTRIBUTING.md to guide contributors" });

  // Duplicate/redundant file patterns
  const mdFiles = files.filter(f => f.path.endsWith(".md")).map(f => f.path);
  const configDupes = [];
  const hasEslintrc = files.filter(f => f.path.match(/\.eslintrc/)).length > 1;
  const hasPrettierrc = files.filter(f => f.path.match(/\.prettierrc/)).length > 1;
  if (hasEslintrc) configDupes.push("Multiple .eslintrc files detected — consolidate to one");
  if (hasPrettierrc) configDupes.push("Multiple .prettierrc files detected — consolidate to one");

  // Large media
  const mediaExtensions = /\.(png|jpg|jpeg|gif|svg|mp4|mov|avi|webm|wav|mp3|pdf)$/i;
  const largeMedia = files
    .filter(f => mediaExtensions.test(f.path) && f.size && f.size > 200000)
    .sort((a, b) => b.size - a.size)
    .slice(0, 10)
    .map(f => ({ path: f.path, size: f.size, ext: f.path.split(".").pop().toLowerCase() }));

  // Repo structure score
  const totalIssues = findings.length + missing.length;
  const criticalCount = findings.filter(f => f.severity === "critical").length + missing.filter(m => m.severity === "critical").length;
  const score = Math.max(0, 100 - (criticalCount * 20) - (findings.filter(f => f.severity === "high").length * 10) - (findings.filter(f => f.severity === "medium").length * 5) - (findings.filter(f => f.severity === "low").length * 2) - (missing.filter(m => m.severity === "critical").length * 15));

  return {
    owner, name: meta.name,
    description: meta.description || "",
    language: Object.keys(langs || {})[0] || "Unknown",
    totalFiles: files.length,
    totalSize: files.reduce((s, f) => s + (f.size || 0), 0),
    findings, missing, largeFiles, largeMedia, configDupes,
    score: Math.min(100, score),
    criticalCount,
    branch,
  };
}

async function generateRecommendations(ctx) {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      model: "claude-sonnet-4-20250514",
      max_tokens: 1000,
      system: "You are a senior DevOps engineer performing a repo health audit. Be specific, direct, and actionable. Return ONLY raw markdown.",
      messages: [{
        role: "user", content: `Perform a cleanup audit for ${ctx.owner}/${ctx.name} (${ctx.language}).

DETECTED ISSUES:
${ctx.findings.map(f => `[${f.severity.toUpperCase()}] ${f.label} (${f.count} files) — ${f.fix}`).join("\n")}

MISSING FILES:
${ctx.missing.map(m => `[${m.severity.toUpperCase()}] ${m.file} — ${m.fix}`).join("\n")}

LARGE MEDIA FILES (${ctx.largeMedia.length}):
${ctx.largeMedia.slice(0, 5).map(f => `${f.path} (${(f.size / 1024).toFixed(0)}KB)`).join("\n")}

TOTAL FILES: ${ctx.totalFiles} | HEALTH SCORE: ${ctx.score}/100 | CRITICAL ISSUES: ${ctx.criticalCount}

Write a brief audit summary (3-5 sentences) followed by:

## 🔴 Critical Actions (do immediately)
Numbered list of critical fixes with exact commands where possible.

## 🟡 Recommended Cleanup
Things that should be done but aren't urgent.

## 📦 Repository Size Optimization
Specific advice about large files and repo bloat if relevant.

## ✅ .gitignore Template
If .gitignore is missing or incomplete, provide a minimal .gitignore for ${ctx.language}.

Be specific to this repo. Use actual file names from the findings.`
      }],
    }),
  });
  const data = await res.json();
  return data.content?.find(b => b.type === "text")?.text || "";
}

function renderMd(md) {
  if (!md) return "";
  return md
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/^#{3} (.+)$/gm, "<h3 style='color:#fed7aa;font-size:1em;margin:.7em 0 .3em'>$1</h3>")
    .replace(/^#{2} (.+)$/gm, "<h2 style='color:#fdba74;font-size:1.1em;border-bottom:1px solid #431407;padding-bottom:.2em;margin:.8em 0 .3em'>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1 style='color:#fb923c;font-size:1.3em;margin:.8em 0 .3em'>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong style='color:#fed7aa'>$1</strong>")
    .replace(/`([^`\n]+)`/g, "<code style='background:#431407;padding:1px 5px;border-radius:4px;font-size:.82em;color:#fb923c;font-family:monospace'>$1</code>")
    .replace(/```[\w]*\n?([\s\S]*?)```/g, (_, c) => `<pre style="background:#1c0a00;padding:12px 14px;border-radius:7px;overflow-x:auto;margin:.5em 0;border:1px solid #431407"><code style="color:#fb923c;font-size:.85em;font-family:'JetBrains Mono',monospace">${c.trim()}</code></pre>`)
    .replace(/^\s*[-*] (.+)$/gm, "<li style='color:#d97706;margin:.25em 0;font-size:13px'>$1</li>")
    .replace(/(<li[\s\S]*?<\/li>\n?)+/g, m => `<ul style="padding-left:16px;margin:.35em 0">${m}</ul>`)
    .replace(/^\d+\. (.+)$/gm, "<li style='color:#d97706;margin:.25em 0;font-size:13px'>$1</li>")
    .replace(/\n\n+/g, "</p><p style='color:#92400e;margin:.4em 0;font-size:13px;line-height:1.75'>")
    .replace(/^(?!<[hpuolridbs]|<hr|<pre)(.+)$/gm, m => m.trim() ? `<p style="color:#92400e;margin:.35em 0;font-size:13px;line-height:1.75">${m}</p>` : "");
}

function formatBytes(b) {
  if (b > 1048576) return (b / 1048576).toFixed(1) + " MB";
  if (b > 1024) return (b / 1024).toFixed(0) + " KB";
  return b + " B";
}

const SEVERITY_CONFIG = {
  critical: { color: "#ef4444", bg: "#450a0a", border: "#7f1d1d", label: "CRITICAL", dot: "🔴" },
  high:     { color: "#f97316", bg: "#431407", border: "#7c2d12", label: "HIGH",     dot: "🟠" },
  medium:   { color: "#eab308", bg: "#422006", border: "#713f12", label: "MEDIUM",   dot: "🟡" },
  low:      { color: "#84cc16", bg: "#1a2e05", border: "#365314", label: "LOW",      dot: "🟢" },
};

function IssueRow({ item, type }) {
  const [open, setOpen] = useState(false);
  const cfg = SEVERITY_CONFIG[item.severity] || SEVERITY_CONFIG.low;
  return (
    <div style={{ border: `1px solid ${cfg.border}`, borderRadius: 8, overflow: "hidden", marginBottom: 6 }}>
      <div onClick={() => setOpen(o => !o)} style={{ display: "flex", alignItems: "center", gap: 10, padding: "10px 13px", cursor: "pointer", background: cfg.bg }}>
        <span style={{ fontSize: 12 }}>{cfg.dot}</span>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: cfg.color }}>{item.label || item.file}</div>
          {item.count && <div style={{ fontSize: 10, color: cfg.color + "99", marginTop: 1 }}>{item.count} file{item.count > 1 ? "s" : ""} affected</div>}
        </div>
        <span style={{ fontSize: 9, padding: "2px 6px", borderRadius: 4, background: cfg.color + "22", color: cfg.color, fontWeight: 800, letterSpacing: "0.05em" }}>{cfg.label}</span>
        <span style={{ color: cfg.color + "80", fontSize: 11 }}>{open ? "▲" : "▼"}</span>
      </div>
      {open && (
        <div style={{ padding: "10px 13px", background: "#0f0500", borderTop: `1px solid ${cfg.border}` }}>
          <div style={{ fontSize: 11, color: "#d97706", lineHeight: 1.6, marginBottom: item.examples?.length ? 8 : 0 }}>
            💡 {item.fix}
          </div>
          {item.examples?.length > 0 && (
            <div style={{ display: "flex", flexWrap: "wrap", gap: 4 }}>
              {item.examples.map(e => (
                <code key={e} style={{ fontSize: 10, padding: "2px 7px", borderRadius: 4, background: "#1c0a00", color: "#fb923c", fontFamily: "'JetBrains Mono',monospace" }}>{e}</code>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function ScoreRing({ score }) {
  const r = 38; const c = 2 * Math.PI * r;
  const dash = (score / 100) * c;
  const color = score >= 80 ? "#4ade80" : score >= 60 ? "#facc15" : score >= 40 ? "#f97316" : "#ef4444";
  return (
    <svg width="100" height="100" viewBox="0 0 100 100">
      <circle cx="50" cy="50" r={r} fill="none" stroke="#1c0a00" strokeWidth="10" />
      <circle cx="50" cy="50" r={r} fill="none" stroke={color} strokeWidth="10"
        strokeDasharray={`${dash} ${c}`} strokeLinecap="round"
        transform="rotate(-90 50 50)" style={{ transition: "stroke-dasharray 1s ease" }} />
      <text x="50" y="46" textAnchor="middle" fill={color} fontSize="18" fontWeight="800" fontFamily="'JetBrains Mono',monospace">{score}</text>
      <text x="50" y="60" textAnchor="middle" fill="#78350f" fontSize="9" fontFamily="sans-serif">/ 100</text>
    </svg>
  );
}

export default function RepoAudit() {
  const [url, setUrl] = useState("");
  const [scanning, setScanning] = useState(false);
  const [scanMsg, setScanMsg] = useState("");
  const [scanError, setScanError] = useState("");
  const [ctx, setCtx] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [report, setReport] = useState(null);
  const [genError, setGenError] = useState("");
  const [tab, setTab] = useState("issues");
  const [copied, setCopied] = useState(false);

  const MSGS = ["Reading file tree…", "Detecting junk files…", "Checking for secrets…", "Scanning file sizes…", "Computing health score…"];

  const scan = async () => {
    const parsed = parseUrl(url.trim());
    if (!parsed) { setScanError("Enter a valid GitHub URL."); return; }
    setScanError(""); setCtx(null); setReport(null); setScanning(true);
    let mi = 0; setScanMsg(MSGS[0]);
    const iv = setInterval(() => { mi = Math.min(mi + 1, MSGS.length - 1); setScanMsg(MSGS[mi]); }, 700);
    try { setCtx(await scanRepo(parsed.owner, parsed.repo)); }
    catch (e) { setScanError(e.message || "Scan failed."); }
    finally { clearInterval(iv); setScanning(false); }
  };

  const generate = async () => {
    if (!ctx) return;
    setGenerating(true); setGenError(""); setReport(null);
    try { setReport(await generateRecommendations(ctx)); }
    catch (e) { setGenError(e.message || "Generation failed."); }
    finally { setGenerating(false); }
  };

  const allIssues = ctx ? [
    ...ctx.findings,
    ...ctx.missing.map(m => ({ ...m, label: `Missing: ${m.file}`, count: null, examples: [] })),
  ].sort((a, b) => {
    const order = { critical: 0, high: 1, medium: 2, low: 3 };
    return (order[a.severity] ?? 4) - (order[b.severity] ?? 4);
  }) : [];

  return (
    <div style={{ minHeight: "100vh", background: "#0f0500", color: "#fed7aa", fontFamily: "'DM Sans','Segoe UI',sans-serif", paddingBottom: 80 }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;700&display=swap');
        *{box-sizing:border-box}
        @keyframes fadein{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
        @keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}
        input::placeholder{color:#431407}
        ::-webkit-scrollbar{width:4px}::-webkit-scrollbar-thumb{background:#431407;border-radius:2px}
      `}</style>

      <div style={{ borderBottom: "1px solid #431407", padding: "15px 26px", display: "flex", alignItems: "center", gap: 12, background: "#1c0a00" }}>
        <div style={{ width: 32, height: 32, borderRadius: 8, background: "linear-gradient(135deg,#9a3412,#c2410c)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16 }}>🔍</div>
        <div>
          <div style={{ fontWeight: 800, fontSize: 15, letterSpacing: "-0.02em", color: "#fb923c" }}>Repo Audit</div>
          <div style={{ fontSize: 11, color: "#78350f" }}>Detect junk, bloat & security risks</div>
        </div>
        {ctx && (
          <div style={{ marginLeft: "auto", display: "flex", gap: 8, alignItems: "center" }}>
            <span style={{ fontSize: 11, color: ctx.criticalCount > 0 ? "#ef4444" : "#4ade80", fontWeight: 700 }}>
              {ctx.criticalCount > 0 ? `⚠ ${ctx.criticalCount} critical` : "✓ No critical issues"}
            </span>
          </div>
        )}
      </div>

      <div style={{ maxWidth: 860, margin: "0 auto", padding: "24px 18px" }}>
        {/* Input */}
        <div style={{ marginBottom: 24 }}>
          <div style={{ fontSize: 11, fontWeight: 700, color: "#78350f", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 6 }}>Repository to Audit</div>
          <div style={{ display: "flex", gap: 8 }}>
            <input value={url} onChange={e => setUrl(e.target.value)}
              onKeyDown={e => e.key === "Enter" && !scanning && scan()}
              placeholder="https://github.com/username/repository"
              style={{ flex: 1, padding: "11px 14px", borderRadius: 8, background: "#1c0a00", border: "1px solid #431407", color: "#fed7aa", fontSize: 14, fontFamily: "inherit", outline: "none", transition: "border-color .2s" }}
              onFocus={e => e.target.style.borderColor = "#f97316"}
              onBlur={e => e.target.style.borderColor = "#431407"} />
            <button onClick={scan} disabled={scanning || !url.trim()}
              style={{ padding: "11px 22px", borderRadius: 8, border: "none", background: scanning || !url.trim() ? "#1c0a00" : "#c2410c", color: scanning || !url.trim() ? "#431407" : "#fff", fontSize: 13, fontWeight: 800, cursor: scanning ? "not-allowed" : "pointer", fontFamily: "inherit" }}>
              {scanning ? scanMsg : "Audit →"}
            </button>
          </div>
          {scanError && <div style={{ marginTop: 6, color: "#ef4444", fontSize: 12 }}>⚠ {scanError}</div>}
          {!ctx && !scanning && (
            <div style={{ marginTop: 8, display: "flex", gap: 6, flexWrap: "wrap", alignItems: "center" }}>
              <span style={{ fontSize: 11, color: "#431407" }}>Try:</span>
              {["tiangolo/fastapi", "facebook/react", "vercel/next.js"].map(eg => (
                <button key={eg} onClick={() => setUrl(`https://github.com/${eg}`)} style={{ padding: "3px 9px", borderRadius: 5, border: "1px solid #431407", background: "transparent", color: "#78350f", fontSize: 11, cursor: "pointer", fontFamily: "inherit" }}>{eg}</button>
              ))}
            </div>
          )}
        </div>

        {ctx && (
          <div style={{ animation: "fadein .35s ease" }}>
            {/* Score banner */}
            <div style={{ display: "flex", gap: 16, alignItems: "center", background: "#1c0a00", border: "1px solid #431407", borderRadius: 12, padding: "18px 22px", marginBottom: 20 }}>
              <ScoreRing score={ctx.score} />
              <div style={{ flex: 1 }}>
                <div style={{ fontWeight: 800, fontSize: 18, color: "#fb923c", marginBottom: 4 }}>{ctx.owner}/{ctx.name}</div>
                <div style={{ fontSize: 12, color: "#78350f", marginBottom: 10 }}>{ctx.description || "No description"} · {ctx.language} · {ctx.totalFiles} files · {formatBytes(ctx.totalSize)}</div>
                <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                  {[
                    [allIssues.filter(i => i.severity === "critical").length, "critical", "#ef4444"],
                    [allIssues.filter(i => i.severity === "high").length, "high", "#f97316"],
                    [allIssues.filter(i => i.severity === "medium").length, "medium", "#eab308"],
                    [allIssues.filter(i => i.severity === "low").length, "low", "#84cc16"],
                  ].map(([count, label, color]) => count > 0 && (
                    <span key={label} style={{ fontSize: 11, padding: "3px 10px", borderRadius: 8, background: color + "15", color, border: `1px solid ${color}30`, fontWeight: 700 }}>
                      {count} {label}
                    </span>
                  ))}
                  {ctx.largeMedia.length > 0 && <span style={{ fontSize: 11, padding: "3px 10px", borderRadius: 8, background: "#3b82f615", color: "#60a5fa", border: "1px solid #3b82f630", fontWeight: 700 }}>{ctx.largeMedia.length} large media files</span>}
                </div>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                <button onClick={generate} disabled={generating}
                  style={{ padding: "10px 18px", borderRadius: 8, border: "none", background: generating ? "#1c0a00" : "#9a3412", color: generating ? "#431407" : "#fed7aa", fontSize: 13, fontWeight: 800, cursor: generating ? "not-allowed" : "pointer", fontFamily: "inherit", whiteSpace: "nowrap" }}>
                  {generating ? "Generating…" : "Generate Full Report"}
                </button>
                {genError && <div style={{ color: "#ef4444", fontSize: 11 }}>⚠ {genError}</div>}
              </div>
            </div>

            {/* Tabs */}
            <div style={{ display: "flex", gap: 4, marginBottom: 14, background: "#1c0a00", padding: 4, borderRadius: 8, border: "1px solid #431407" }}>
              {[
                ["issues", `Issues (${allIssues.length})`],
                ["media", `Large Files (${ctx.largeMedia.length})`],
                ...(report ? [["report", "AI Report"]] : []),
              ].map(([id, label]) => (
                <button key={id} onClick={() => setTab(id)}
                  style={{ flex: 1, padding: "7px", borderRadius: 6, border: "none", background: tab === id ? "#431407" : "transparent", color: tab === id ? "#fb923c" : "#78350f", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" }}>
                  {label}
                </button>
              ))}
            </div>

            {/* Issues tab */}
            {tab === "issues" && (
              <div style={{ animation: "fadein .2s ease" }}>
                {allIssues.length === 0
                  ? <div style={{ textAlign: "center", padding: 40, color: "#4ade80" }}>✓ No issues detected — clean repo!</div>
                  : allIssues.map((issue, i) => <IssueRow key={i} item={issue} />)
                }
              </div>
            )}

            {/* Large files tab */}
            {tab === "media" && (
              <div style={{ animation: "fadein .2s ease" }}>
                {ctx.largeMedia.length === 0
                  ? <div style={{ textAlign: "center", padding: 40, color: "#78350f" }}>No large media files detected</div>
                  : (
                    <div style={{ background: "#1c0a00", border: "1px solid #431407", borderRadius: 10, overflow: "hidden" }}>
                      <div style={{ padding: "8px 14px", borderBottom: "1px solid #431407", fontSize: 10, fontWeight: 700, color: "#78350f", textTransform: "uppercase", letterSpacing: "0.1em" }}>
                        Files over 200KB — consider Git LFS or CDN hosting
                      </div>
                      {ctx.largeMedia.map((f, i) => (
                        <div key={i} style={{ display: "flex", gap: 10, alignItems: "center", padding: "9px 14px", borderBottom: "1px solid #0f0500" }}>
                          <span style={{ fontSize: 13, flexShrink: 0 }}>
                            {{ png: "🖼", jpg: "🖼", jpeg: "🖼", gif: "🎞", svg: "🎨", mp4: "🎬", mov: "🎬", pdf: "📄", wav: "🔊", mp3: "🔊" }[f.ext] || "📁"}
                          </span>
                          <code style={{ flex: 1, fontSize: 11, color: "#d97706", fontFamily: "'JetBrains Mono',monospace", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{f.path}</code>
                          <span style={{ fontSize: 11, fontWeight: 700, color: f.size > 1048576 ? "#ef4444" : "#f97316", flexShrink: 0, fontFamily: "'JetBrains Mono',monospace" }}>{formatBytes(f.size)}</span>
                        </div>
                      ))}
                      <div style={{ padding: "10px 14px", background: "#0f0500" }}>
                        <div style={{ fontSize: 11, color: "#78350f" }}>💡 Use <code style={{ background: "#1c0a00", padding: "1px 5px", borderRadius: 3, color: "#fb923c", fontSize: 10 }}>git lfs track "*.png"</code> for large media files</div>
                      </div>
                    </div>
                  )
                }
              </div>
            )}

            {/* AI Report tab */}
            {tab === "report" && report && (
              <div style={{ animation: "fadein .2s ease" }}>
                <div style={{ border: "1px solid #431407", borderRadius: 10, overflow: "hidden" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "9px 14px", background: "#1c0a00", borderBottom: "1px solid #431407" }}>
                    <span style={{ fontSize: 12, fontWeight: 700, color: "#fb923c" }}>🔍 Full Audit Report</span>
                    <div style={{ flex: 1 }} />
                    <button onClick={() => { navigator.clipboard.writeText(report); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
                      style={{ padding: "4px 10px", borderRadius: 6, border: "1px solid #431407", background: copied ? "#1a2e05" : "#1c0a00", color: copied ? "#4ade80" : "#78350f", fontSize: 11, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" }}>
                      {copied ? "✓ Copied" : "⎘ Copy"}
                    </button>
                  </div>
                  <div style={{ padding: "18px 22px", maxHeight: 500, overflowY: "auto" }} dangerouslySetInnerHTML={{ __html: renderMd(report) }} />
                </div>
              </div>
            )}
          </div>
        )}

        {!ctx && !scanning && !scanError && (
          <div style={{ textAlign: "center", padding: "50px 0", color: "#431407" }}>
            <div style={{ fontSize: 44, marginBottom: 14 }}>🔍</div>
            <div style={{ fontWeight: 700, fontSize: 16, color: "#78350f", marginBottom: 6 }}>Audit any public GitHub repo</div>
            <div style={{ fontSize: 12, color: "#431407", maxWidth: 420, margin: "0 auto", lineHeight: 1.85 }}>
              Scans for committed secrets, junk files, build artifacts, large media, missing essentials, and generates a prioritised cleanup plan.
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
